-- DB-driven CLD stage completion: activate payment milestones + enqueue demand letter PDF jobs.
-- Demand letters are generated by the app worker (Playwright); they are NOT auto-sent to customers.

-- -----------------------------------------------------------------------------
-- Demand letter generation queue (one job per completion)
-- -----------------------------------------------------------------------------

create table if not exists public.cld_demand_letter_jobs (
  id uuid primary key default gen_random_uuid(),
  completion_id uuid not null references public.cld_stage_completions (id) on delete cascade,
  project_id uuid not null references public.projects (id) on delete cascade,
  stage_id uuid not null references public.project_cld_stages (id) on delete cascade,
  status text not null default 'queued',
  attempts int not null default 0,
  last_error text,
  demand_letters_generated int not null default 0,
  demand_letters_skipped int not null default 0,
  scheduled_for timestamptz not null default now(),
  processed_at timestamptz,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cld_demand_letter_jobs_status_chk
    check (status in ('queued', 'processing', 'done', 'failed', 'cancelled')),
  constraint cld_demand_letter_jobs_completion_unique unique (completion_id)
);

create index if not exists cld_demand_letter_jobs_pick_idx
  on public.cld_demand_letter_jobs (status, scheduled_for, created_at);

create index if not exists cld_demand_letter_jobs_project_idx
  on public.cld_demand_letter_jobs (project_id, status, scheduled_for);

alter table public.cld_demand_letter_jobs enable row level security;

create policy "cld_demand_letter_jobs_select_project"
on public.cld_demand_letter_jobs
for select
using (public.has_project_access(project_id));

create policy "cld_demand_letter_jobs_mutate_project"
on public.cld_demand_letter_jobs
for all
using (public.has_project_access(project_id))
with check (public.has_project_access(project_id));

create or replace function public.cld_demand_letter_jobs_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists cld_demand_letter_jobs_touch_updated_at on public.cld_demand_letter_jobs;
create trigger cld_demand_letter_jobs_touch_updated_at
before update on public.cld_demand_letter_jobs
for each row execute function public.cld_demand_letter_jobs_touch_updated_at();

-- Resolve booking token amount from column or stage_data JSON.
create or replace function public.cld_resolve_booking_amount_inr(
  p_booking_amount numeric,
  p_stage_data jsonb
)
returns numeric
language sql
immutable
as $$
  select greatest(
    0,
    round(
      coalesce(
        nullif(coalesce(p_booking_amount, 0), 0),
        nullif(
          regexp_replace(coalesce(p_stage_data #>> '{token,amount}', ''), ',', '', 'g')::numeric,
          0
        ),
        0
      )
    )
  );
$$;

revoke all on function public.cld_resolve_booking_amount_inr(numeric, jsonb) from public;
grant execute on function public.cld_resolve_booking_amount_inr(numeric, jsonb) to authenticated;

-- Instalment number (1-based) for a stage within a project.
create or replace function public.cld_instalment_no_for_stage(
  p_project_id uuid,
  p_stage_id uuid
)
returns int
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select s.rn::int
  from (
    select
      st.id,
      row_number() over (order by st.sort_order asc, st.created_at asc) as rn
    from public.project_cld_stages st
    where st.project_id = p_project_id
  ) s
  where s.id = p_stage_id;
$$;

revoke all on function public.cld_instalment_no_for_stage(uuid, uuid) from public;
grant execute on function public.cld_instalment_no_for_stage(uuid, uuid) to authenticated;

create or replace function public.cld_stage_demand_amount(
  p_demand_kind text,
  p_demand_value numeric,
  p_target numeric,
  p_instalment_no int,
  p_booking_amount numeric
)
returns numeric
language sql
immutable
as $$
  select case
    when p_instalment_no = 1 and p_booking_amount > 0 then p_booking_amount
    when p_demand_kind = 'fixed' then greatest(0, round(coalesce(p_demand_value, 0)))
    else greatest(0, round((p_target * coalesce(p_demand_value, 0)) / 100))
  end;
$$;

revoke all on function public.cld_stage_demand_amount(text, numeric, numeric, int, numeric) from public;
grant execute on function public.cld_stage_demand_amount(text, numeric, numeric, int, numeric) to authenticated;

-- Apply a logged CLD completion to every non-cancelled booking on the project.
create or replace function public.apply_cld_stage_completion(p_completion_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  v_project_id uuid;
  v_stage_id uuid;
  v_completed_on date;
  v_created_by uuid;
  v_instalment_no int;
  v_milestone text;
  v_demand_kind text;
  v_demand_value numeric;
  v_bookings_processed int := 0;
  v_schedules_updated int := 0;
  v_job_id uuid;
  r record;
  v_booking_amount numeric;
  v_sale_total numeric;
  v_target numeric;
  v_amount numeric;
  v_schedule_id uuid;
  v_schedule_count int;
begin
  if p_completion_id is null then
    return jsonb_build_object('ok', false, 'error', 'completion_id_required');
  end if;

  select
    c.project_id,
    c.stage_id,
    c.completed_on,
    c.created_by
  into v_project_id, v_stage_id, v_completed_on, v_created_by
  from public.cld_stage_completions c
  where c.id = p_completion_id;

  if v_project_id is null then
    return jsonb_build_object('ok', false, 'error', 'completion_not_found');
  end if;

  if not public.is_cld_eligible_project(v_project_id) then
    return jsonb_build_object('ok', true, 'skipped', true, 'reason', 'project_not_eligible');
  end if;

  select
    public.cld_instalment_no_for_stage(v_project_id, v_stage_id),
    public.cld_milestone_label(s.name, s.slab_label),
    s.demand_kind,
    s.demand_value
  into v_instalment_no, v_milestone, v_demand_kind, v_demand_value
  from public.project_cld_stages s
  where s.id = v_stage_id
    and s.project_id = v_project_id;

  if v_instalment_no is null then
    return jsonb_build_object('ok', false, 'error', 'cld_stage_not_found');
  end if;

  for r in
    select
      b.id as booking_id,
      coalesce(b.booking_amount, 0) as booking_amount,
      coalesce(b.sale_total_inr, 0) as sale_total_inr,
      b.stage_data
    from public.bookings b
    where b.project_id = v_project_id
      and b.status <> 'cancelled'
  loop
    v_bookings_processed := v_bookings_processed + 1;

    v_booking_amount := public.cld_resolve_booking_amount_inr(r.booking_amount, r.stage_data);
    v_sale_total := greatest(0, round(r.sale_total_inr));
    v_target := greatest(v_sale_total, v_booking_amount);
    v_amount := public.cld_stage_demand_amount(
      v_demand_kind,
      v_demand_value,
      v_target,
      v_instalment_no,
      v_booking_amount
    );

    select ps.id
    into v_schedule_id
    from public.payment_schedules ps
    where ps.booking_id = r.booking_id
      and ps.instalment_no = v_instalment_no;

    if v_schedule_id is not null then
      update public.payment_schedules ps
      set
        due_date = v_completed_on,
        milestone = v_milestone,
        amount = case
          when coalesce(ps.amount, 0) <= 0 and v_amount > 0 then v_amount
          else ps.amount
        end
      where ps.id = v_schedule_id;
      v_schedules_updated := v_schedules_updated + 1;
      continue;
    end if;

    select count(*)::int
    into v_schedule_count
    from public.payment_schedules ps
    where ps.booking_id = r.booking_id;

    if v_schedule_count <= 0 then
      perform public.rebuild_payment_schedule_for_booking(r.booking_id);

      update public.payment_schedules ps
      set
        due_date = v_completed_on,
        milestone = v_milestone
      where ps.booking_id = r.booking_id
        and ps.instalment_no = v_instalment_no;

      if found then
        v_schedules_updated := v_schedules_updated + 1;
      end if;
      continue;
    end if;

    insert into public.payment_schedules (booking_id, instalment_no, milestone, due_date, amount)
    values (r.booking_id, v_instalment_no, v_milestone, v_completed_on, v_amount);
    v_schedules_updated := v_schedules_updated + 1;
  end loop;

  insert into public.cld_demand_letter_jobs (
    completion_id,
    project_id,
    stage_id,
    created_by,
    status,
    scheduled_for
  )
  values (
    p_completion_id,
    v_project_id,
    v_stage_id,
    v_created_by,
    'queued',
    now()
  )
  on conflict (completion_id) do update
  set
    status = 'queued',
    scheduled_for = now(),
    last_error = null
  returning id into v_job_id;

  return jsonb_build_object(
    'ok', true,
    'completion_id', p_completion_id,
    'bookings_processed', v_bookings_processed,
    'schedules_updated', v_schedules_updated,
    'demand_letter_job_id', v_job_id
  );
exception
  when others then
    return jsonb_build_object('ok', false, 'error', sqlerrm);
end;
$$;

revoke all on function public.apply_cld_stage_completion(uuid) from public;
grant execute on function public.apply_cld_stage_completion(uuid) to authenticated;
grant execute on function public.apply_cld_stage_completion(uuid) to service_role;

create or replace function public.trg_cld_stage_completions_apply()
returns trigger
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  v_result jsonb;
begin
  v_result := public.apply_cld_stage_completion(new.id);

  if coalesce((v_result->>'ok')::boolean, false) is not true
     and coalesce(v_result->>'skipped', 'false') <> 'true' then
    raise exception 'apply_cld_stage_completion failed: %',
      coalesce(v_result->>'error', v_result::text);
  end if;

  return new;
end;
$$;

drop trigger if exists cld_stage_completions_apply on public.cld_stage_completions;
create trigger cld_stage_completions_apply
after insert on public.cld_stage_completions
for each row execute function public.trg_cld_stage_completions_apply();

-- Claim + complete demand letter jobs (PDF generation happens in the app worker).
create or replace function public.claim_cld_demand_letter_job(p_job_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  v_row public.cld_demand_letter_jobs%rowtype;
begin
  update public.cld_demand_letter_jobs j
  set
    status = 'processing',
    attempts = j.attempts + 1,
    last_error = null
  where j.id = p_job_id
    and j.status = 'queued'
  returning j.* into v_row;

  if v_row.id is null then
    return jsonb_build_object('ok', false, 'error', 'job_not_queued_or_missing');
  end if;

  return jsonb_build_object(
    'ok', true,
    'job_id', v_row.id,
    'completion_id', v_row.completion_id,
    'project_id', v_row.project_id,
    'stage_id', v_row.stage_id,
    'created_by', v_row.created_by
  );
end;
$$;

revoke all on function public.claim_cld_demand_letter_job(uuid) from public;
grant execute on function public.claim_cld_demand_letter_job(uuid) to service_role;

create or replace function public.complete_cld_demand_letter_job(
  p_job_id uuid,
  p_generated int default 0,
  p_skipped int default 0,
  p_error text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
begin
  if p_error is not null and btrim(p_error) <> '' then
    update public.cld_demand_letter_jobs
    set
      status = 'failed',
      last_error = btrim(p_error),
      demand_letters_generated = greatest(0, coalesce(p_generated, 0)),
      demand_letters_skipped = greatest(0, coalesce(p_skipped, 0)),
      processed_at = now()
    where id = p_job_id;
    return jsonb_build_object('ok', true, 'status', 'failed');
  end if;

  update public.cld_demand_letter_jobs
  set
    status = 'done',
    last_error = null,
    demand_letters_generated = greatest(0, coalesce(p_generated, 0)),
    demand_letters_skipped = greatest(0, coalesce(p_skipped, 0)),
    processed_at = now()
  where id = p_job_id;

  return jsonb_build_object('ok', true, 'status', 'done');
end;
$$;

revoke all on function public.complete_cld_demand_letter_job(uuid, int, int, text) from public;
grant execute on function public.complete_cld_demand_letter_job(uuid, int, int, text) to service_role;

create or replace function public.pick_next_cld_demand_letter_job()
returns uuid
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  v_job_id uuid;
begin
  select j.id
  into v_job_id
  from public.cld_demand_letter_jobs j
  where j.status = 'queued'
    and j.scheduled_for <= now()
  order by j.scheduled_for asc, j.created_at asc
  for update skip locked
  limit 1;

  return v_job_id;
end;
$$;

revoke all on function public.pick_next_cld_demand_letter_job() from public;
grant execute on function public.pick_next_cld_demand_letter_job() to service_role;
