export const INDIAN_STATE_CITIES: Record<string, string[]> = {
  'Andhra Pradesh': [
    'Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Krishna',
    'Kurnool', 'Nellore', 'Prakasam', 'Srikakulam', 'Visakhapatnam',
    'Vizianagaram', 'West Godavari', 'YSR Kadapa', 'Tirupati',
    'Vijayawada', 'Kakinada', 'Rajahmundry', 'Eluru', 'Ongole',
    'Nandyal', 'Machilipatnam', 'Adoni', 'Tenali', 'Proddatur',
    'Hindupur', 'Bhimavaram', 'Madanapalle', 'Guntakal',
  ],
  'Arunachal Pradesh': [
    'Itanagar', 'Tawang', 'West Kameng', 'East Kameng', 'Papum Pare',
    'Kurung Kumey', 'Lower Subansiri', 'Upper Subansiri', 'West Siang',
    'East Siang', 'Upper Siang', 'Changlang', 'Tirap', 'Lohit',
    'Anjaw', 'Dibang Valley', 'Lower Dibang Valley', 'Naharlagun',
  ],
  'Assam': [
    'Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon',
    'Tinsukia', 'Tezpur', 'Bongaigaon', 'Dhubri', 'Kamrup',
    'Kamrup Metropolitan', 'Cachar', 'Darrang', 'Goalpara',
    'Karimganj', 'Kokrajhar', 'Lakhimpur', 'Morigaon', 'Nalbari',
    'Sivasagar', 'Sonitpur', 'Barpeta', 'Golaghat',
  ],
  'Bihar': [
    'Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Darbhanga',
    'Purnia', 'Arrah', 'Begusarai', 'Katihar', 'Munger',
    'Chapra', 'Sasaram', 'Hajipur', 'Bihar Sharif', 'Dehri',
    'Siwan', 'Motihari', 'Nawada', 'Bettiah', 'Saharsa',
    'Nalanda', 'Vaishali', 'Samastipur', 'Madhubani', 'Sitamarhi',
    'Jehanabad', 'Aurangabad', 'Buxar', 'Kishanganj', 'Jamui',
    'East Champaran', 'West Champaran', 'Gopalganj', 'Saran',
    'Khagaria', 'Madhepura', 'Supaul', 'Araria', 'Lakhisarai',
    'Sheikhpura', 'Rohtas', 'Kaimur', 'Bhojpur',
  ],
  'Chhattisgarh': [
    'Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg',
    'Rajnandgaon', 'Jagdalpur', 'Raigarh', 'Ambikapur',
    'Dhamtari', 'Mahasamund', 'Kanker', 'Kawardha',
    'Janjgir-Champa', 'Surguja', 'Bastar', 'Dantewada',
    'Gariaband', 'Balod', 'Bemetara', 'Mungeli',
  ],
  'Goa': [
    'Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda',
    'North Goa', 'South Goa', 'Bicholim', 'Curchorem',
    'Sanquelim', 'Canacona', 'Quepem', 'Sanguem',
  ],
  'Gujarat': [
    'Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar',
    'Jamnagar', 'Junagadh', 'Gandhinagar', 'Anand', 'Nadiad',
    'Morbi', 'Mehsana', 'Bharuch', 'Vapi', 'Navsari',
    'Veraval', 'Porbandar', 'Godhra', 'Palanpur', 'Valsad',
    'Patan', 'Dahod', 'Botad', 'Amreli', 'Deesa',
    'Jetpur', 'Surendranagar', 'Kutch', 'Kheda', 'Sabarkantha',
    'Banaskantha', 'Panchmahals', 'Mahisagar', 'Narmada',
    'Aravalli', 'Gir Somnath', 'Devbhumi Dwarka', 'Tapi',
    'Dang', 'Chhota Udaipur',
  ],
  'Haryana': [
    'Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Karnal',
    'Hisar', 'Rohtak', 'Sonipat', 'Yamunanagar', 'Panchkula',
    'Bhiwani', 'Sirsa', 'Jind', 'Thanesar', 'Kaithal',
    'Palwal', 'Rewari', 'Fatehabad', 'Mahendragarh', 'Nuh',
    'Charkhi Dadri', 'Kurukshetra',
  ],
  'Himachal Pradesh': [
    'Shimla', 'Dharamshala', 'Mandi', 'Solan', 'Kullu',
    'Bilaspur', 'Hamirpur', 'Una', 'Chamba', 'Kangra',
    'Nahan', 'Palampur', 'Manali', 'Kinnaur', 'Lahaul and Spiti',
    'Sirmaur',
  ],
  'Jharkhand': [
    'Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar',
    'Hazaribagh', 'Giridih', 'Ramgarh', 'Dumka', 'Medininagar',
    'Chaibasa', 'Phusro', 'Chirkunda', 'East Singhbhum',
    'West Singhbhum', 'Palamu', 'Saraikela Kharsawan',
    'Latehar', 'Chatra', 'Garhwa', 'Koderma', 'Lohardaga',
    'Gumla', 'Simdega', 'Sahibganj', 'Godda', 'Pakur', 'Jamtara',
  ],
  'Karnataka': [
    'Bengaluru', 'Mysuru', 'Mangaluru', 'Hubballi', 'Belagavi',
    'Kalaburagi', 'Davanagere', 'Ballari', 'Vijayapura', 'Shimoga',
    'Tumkur', 'Raichur', 'Bidar', 'Hospet', 'Hassan',
    'Gadag', 'Udupi', 'Chikkamagaluru', 'Dharwad', 'Bagalkot',
    'Haveri', 'Chitradurga', 'Mandya', 'Chamarajanagar',
    'Kodagu', 'Ramanagara', 'Chikkaballapur', 'Yadgir', 'Koppal',
    'Bangalore Rural', 'Bangalore Urban', 'Uttara Kannada',
    'Dakshina Kannada',
  ],
  'Kerala': [
    'Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur',
    'Kollam', 'Alappuzha', 'Palakkad', 'Malappuram', 'Kannur',
    'Kottayam', 'Ernakulam', 'Pathanamthitta', 'Idukki',
    'Wayanad', 'Kasaragod',
  ],
  'Madhya Pradesh': [
    'Bhopal', 'Indore', 'Jabalpur', 'Gwalior', 'Ujjain',
    'Sagar', 'Dewas', 'Satna', 'Ratlam', 'Rewa',
    'Katni', 'Singrauli', 'Burhanpur', 'Khandwa', 'Morena',
    'Bhind', 'Chhindwara', 'Shivpuri', 'Vidisha', 'Damoh',
    'Hoshangabad', 'Mandsaur', 'Neemuch', 'Sehore', 'Betul',
    'Tikamgarh', 'Panna', 'Seoni', 'Dhar', 'Jhabua',
    'Shahdol', 'Balaghat', 'Mandla', 'Narsinghpur',
    'Rajgarh', 'Datia', 'Ashok Nagar', 'Shajapur',
    'Harda', 'Agar Malwa', 'Alirajpur', 'Anuppur', 'Barwani',
    'Dindori', 'Umaria',
  ],
  'Maharashtra': [
    'Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik',
    'Aurangabad', 'Solapur', 'Kolhapur', 'Amravati', 'Nanded',
    'Sangli', 'Jalgaon', 'Akola', 'Latur', 'Ahmednagar',
    'Dhule', 'Chandrapur', 'Parbhani', 'Jalna', 'Bhiwandi',
    'Panvel', 'Satara', 'Beed', 'Yavatmal', 'Osmanabad',
    'Nandurbar', 'Wardha', 'Washim', 'Hingoli', 'Buldhana',
    'Gondia', 'Gadchiroli', 'Ratnagiri', 'Sindhudurg',
    'Raigad', 'Palghar', 'Mumbai City', 'Mumbai Suburban',
  ],
  'Manipur': [
    'Imphal', 'Thoubal', 'Bishnupur', 'Churachandpur',
    'Imphal East', 'Imphal West', 'Senapati', 'Ukhrul',
    'Chandel', 'Tamenglong',
  ],
  'Meghalaya': [
    'Shillong', 'Tura', 'Jowai', 'Nongstoin', 'Williamnagar',
    'East Khasi Hills', 'West Khasi Hills', 'East Garo Hills',
    'West Garo Hills', 'South Garo Hills', 'Ri Bhoi',
    'East Jaintia Hills', 'West Jaintia Hills',
  ],
  'Mizoram': [
    'Aizawl', 'Lunglei', 'Champhai', 'Serchhip', 'Kolasib',
    'Lawngtlai', 'Mamit', 'Saiha',
  ],
  'Nagaland': [
    'Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha',
    'Zunheboto', 'Mon', 'Phek', 'Kiphire', 'Longleng', 'Peren',
  ],
  'Odisha': [
    'Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur', 'Sambalpur',
    'Puri', 'Balasore', 'Bhadrak', 'Baripada', 'Jharsuguda',
    'Jeypore', 'Bargarh', 'Angul', 'Dhenkanal', 'Keonjhar',
    'Sundargarh', 'Koraput', 'Rayagada', 'Ganjam', 'Khordha',
    'Jagatsinghpur', 'Jajpur', 'Kendrapara', 'Mayurbhanj',
    'Bolangir', 'Kalahandi', 'Nabarangpur', 'Nuapada',
    'Nayagarh', 'Kandhamal', 'Malkangiri', 'Gajapati',
    'Boudh', 'Sonepur', 'Deogarh',
  ],
  'Punjab': [
    'Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda',
    'Mohali', 'Pathankot', 'Hoshiarpur', 'Batala', 'Moga',
    'Abohar', 'Malerkotla', 'Khanna', 'Muktsar', 'Barnala',
    'Rajpura', 'Firozpur', 'Kapurthala', 'Faridkot', 'Sangrur',
    'Fazilka', 'Gurdaspur', 'Mansa', 'Rupnagar', 'Nawanshahr',
    'Tarn Taran',
  ],
  'Rajasthan': [
    'Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Ajmer',
    'Bikaner', 'Bhilwara', 'Alwar', 'Sikar', 'Bharatpur',
    'Pali', 'Sri Ganganagar', 'Tonk', 'Kishangarh', 'Beawar',
    'Hanumangarh', 'Dhaulpur', 'Gangapur City', 'Sawai Madhopur',
    'Barmer', 'Churu', 'Jhunjhunu', 'Nagaur', 'Chittorgarh',
    'Bundi', 'Baran', 'Jhalawar', 'Dungarpur', 'Banswara',
    'Pratapgarh', 'Rajsamand', 'Karauli', 'Dausa', 'Jalore',
    'Sirohi', 'Jaisalmer',
  ],
  'Sikkim': [
    'Gangtok', 'Namchi', 'Mangan', 'Gyalshing', 'Rangpo',
    'Singtam', 'Jorethang', 'East Sikkim', 'West Sikkim',
    'North Sikkim', 'South Sikkim',
  ],
  'Tamil Nadu': [
    'Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem',
    'Tirunelveli', 'Tiruppur', 'Erode', 'Vellore', 'Thoothukudi',
    'Dindigul', 'Thanjavur', 'Ranipet', 'Sivakasi', 'Karur',
    'Nagercoil', 'Kanchipuram', 'Cuddalore', 'Kumbakonam',
    'Rajapalayam', 'Pudukkottai', 'Hosur', 'Nagapattinam',
    'Viluppuram', 'Dharmapuri', 'Krishnagiri', 'Namakkal',
    'Perambalur', 'Ariyalur', 'Nilgiris', 'Kallakurichi',
    'Chengalpattu', 'Tirupattur', 'Tiruvannamalai', 'Sivaganga',
    'Virudhunagar', 'Theni', 'Ramanathapuram', 'Tenkasi',
    'Mayiladuthurai',
  ],
  'Telangana': [
    'Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam',
    'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet', 'Miryalaguda',
    'Ramagundam', 'Siddipet', 'Mancherial', 'Kamareddy',
    'Jagtial', 'Nirmal', 'Wanaparthy', 'Medak', 'Sangareddy',
    'Rangareddy', 'Medchal-Malkajgiri', 'Yadadri Bhuvanagiri',
    'Jogulamba Gadwal', 'Vikarabad', 'Narayanpet', 'Mahabubabad',
    'Rajanna Sircilla', 'Jayashankar Bhupalpally', 'Mulugu',
    'Nagarkurnool', 'Peddapalli', 'Kumuram Bheem Asifabad',
    'Jangaon', 'Bhadradri Kothagudem',
  ],
  'Tripura': [
    'Agartala', 'Udaipur', 'Dharmanagar', 'Kailasahar',
    'Belonia', 'Ambassa', 'Khowai', 'West Tripura',
    'South Tripura', 'North Tripura', 'Dhalai', 'Gomati',
    'Sepahijala', 'Unakoti',
  ],
  'Uttar Pradesh': [
    'Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Meerut',
    'Prayagraj', 'Ghaziabad', 'Noida', 'Bareilly', 'Aligarh',
    'Moradabad', 'Gorakhpur', 'Saharanpur', 'Jhansi', 'Muzaffarnagar',
    'Mathura', 'Firozabad', 'Ayodhya', 'Shahjahanpur', 'Rampur',
    'Unnao', 'Lakhimpur Kheri', 'Sitapur', 'Hardoi', 'Rae Bareli',
    'Sultanpur', 'Fatehpur', 'Pratapgarh', 'Banda', 'Jaunpur',
    'Mirzapur', 'Sonbhadra', 'Chandauli', 'Bhadohi', 'Ghazipur',
    'Ballia', 'Mau', 'Azamgarh', 'Deoria', 'Kushinagar',
    'Maharajganj', 'Basti', 'Sant Kabir Nagar', 'Siddharth Nagar',
    'Ambedkar Nagar', 'Barabanki', 'Bahraich', 'Shravasti',
    'Balrampur', 'Gonda', 'Etawah', 'Mainpuri', 'Budaun',
    'Sambhal', 'Amroha', 'Bijnor', 'Hapur', 'Bulandshahr',
    'Hathras', 'Kasganj', 'Etah', 'Farrukhabad', 'Kannauj',
    'Auraiya', 'Hamirpur', 'Mahoba', 'Lalitpur', 'Chitrakoot',
    'Pilibhit', 'Gautam Buddha Nagar',
  ],
  'Uttarakhand': [
    'Dehradun', 'Haridwar', 'Rishikesh', 'Haldwani', 'Roorkee',
    'Kashipur', 'Rudrapur', 'Nainital', 'Almora', 'Pithoragarh',
    'Chamoli', 'Tehri Garhwal', 'Pauri Garhwal', 'Udham Singh Nagar',
    'Bageshwar', 'Champawat', 'Uttarkashi',
  ],
  'West Bengal': [
    'Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Siliguri',
    'Bardhaman', 'Malda', 'Baharampur', 'Habra', 'Kharagpur',
    'Shantipur', 'Haldia', 'Raiganj', 'Krishnanagar', 'Nabadwip',
    'Medinipur', 'Bankura', 'Purulia', 'Jalpaiguri', 'Cooch Behar',
    'Darjeeling', 'Alipurduar', 'North 24 Parganas',
    'South 24 Parganas', 'Hooghly', 'Nadia', 'Murshidabad',
    'Birbhum', 'East Midnapore', 'West Midnapore', 'Jhargram',
    'Kalimpong', 'Uttar Dinajpur', 'Dakshin Dinajpur',
  ],
  'Andaman and Nicobar Islands': [
    'Port Blair', 'Nicobar', 'North and Middle Andaman',
    'South Andaman',
  ],
  'Chandigarh': ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Silvassa', 'Daman', 'Diu',
  ],
  'Delhi': [
    'New Delhi', 'Central Delhi', 'East Delhi', 'North Delhi',
    'North East Delhi', 'North West Delhi', 'South Delhi',
    'South East Delhi', 'South West Delhi', 'West Delhi',
    'Shahdara',
  ],
  'Jammu and Kashmir': [
    'Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Kathua',
    'Udhampur', 'Rajouri', 'Poonch', 'Doda', 'Kishtwar',
    'Ramban', 'Reasi', 'Samba', 'Kupwara', 'Bandipora',
    'Ganderbal', 'Pulwama', 'Shopian', 'Kulgam', 'Budgam',
  ],
  'Ladakh': ['Leh', 'Kargil'],
  'Lakshadweep': ['Kavaratti', 'Agatti', 'Minicoy'],
  'Puducherry': ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
};

/** Return sorted cities for a state, or empty array if state unknown */
export function getCitiesForState(state: string): string[] {
  return (INDIAN_STATE_CITIES[state] ?? []).slice().sort();
}
